image: eeacms/rsync

pipelines:
  branches:
    #staging:
      # step:
        # add steps here to deploy to staging server if you want, otherwise just only run on merge to master
    master:
      - step:
          name: Deploy to Prod
          deployment: production
          script:
            - DESTINATION_PATH="/home/dh_uey5n8/backup/"
            - ssh-keygen -t rsa -b 4096 -f /opt/atlassian/pipelines/agent/ssh/id_rsa -N ""
            - chmod 600 /opt/atlassian/pipelines/agent/ssh/id_rsa
            - rsync -hrvPt -e "ssh -i /opt/atlassian/pipelines/agent/ssh/id_rsa" . $USER@$SERVER:$DESTINATION_PATH --exclude='Google_Postmaster/' --exclude='.git/' --itemize-changes | grep -E '^[<f]' | awk '{print $2}'