image: eeacms/rsync

pipelines:
  branches:
    #staging:
      # step:
        # add steps here to deploy to staging server if you want, otherwise just only run on merge to master
    master:
      - step:
          name: Deploy to Prod
          deployment: production
          script:
            - rsync -hvrPt . $USER@$SERVER:/home/dh_uey5n8/backup/ --exclude='Google_Postmaster/' --exclude='.git/' --itemize-changes
            # - pipe: atlassian/scp-deploy:1.4.1
              # variables:
               #  USER: $USER
               #  SERVER: $SERVER
               #  REMOTE_PATH: '/home/dh_uey5n8/imscrm.com/'
               #  LOCAL_PATH: '*'
                # DEBUG: 'true'