options:
  max-time: 2  # time in minutes

image: eeacms/rsync

pipelines:
  branches:
    #staging:
      # step:
        # add steps here to deploy to staging server if you want, otherwise just only run on merge to master
    master:
      - step:
          name: Timeout Test
          script:
            - sleep 200  # Sleep for longer than 2 minutes
      - step:
          name: Deploy to Prod
          deployment: production
          script:
            - DESTINATION_PATH="/home/dh_uey5n8/imscrm.com/"
            - rsync -azlhi . $USER@$SERVER:$DESTINATION_PATH --exclude='Google_Postmaster/' --exclude='.git/' | grep -E '^[<f]' | awk '{print $2}'