image: node:10.15.3

pipelines:
  default:
    - step:
        name: Deploy to $SERVER
        deployment: production
        script:
          - pipe: atlassian/scp-deploy:1.4.1
            variables:
              USER: $USER
              SERVER: $SERVER
              REMOTE_PATH: '/home/dh_uey5n8/tmp/'
              LOCAL_PATH: 'bin/*'
              # DEBUG: 'true'