image: node:10.15.3

pipelines:
  branches:
    #staging:
      # step:
        # add steps here to deploy to staging server if you want, otherwise just only run on merge to master
    master:
      - step:
          name: Deploy to Prod
          deployment: production
          script:
            - pipe: atlassian/scp-deploy:1.4.1
              variables:
                USER: $USER
                SERVER: $SERVER
                REMOTE_PATH: '/home/dh_uey5n8/tmp/'
                LOCAL_PATH: 'bin/*'
                # DEBUG: 'true'